server:
  port: 8090
#  context-path: /consumer-rabbitmq
spring:
  application:
    name: microservice-consumer-rabbitmq
  rabbitmq:
    host: 192.168.35.153
    port: 5672
    username: admin
    password: 12345678
  cloud:
    stream:
      default-binder: matrix
      bindings:
        matrix: 
          group: group1
          destination: dest1
      binders:
        matrix: 
          type: rabbit
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    healthcheck: 
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:  
  security:  
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false ,否则很多点监控不到 

info:  
  app:  
    name: "@project.name@"  
    description: "@project.description@"  
    version: "@project.version@"  
    spring-boot-version: "@project.parent.version@"