server:
  port: 8090
#  context-path: /consumer
spring:
  application:
    name: microservice-consumer
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    healthcheck: 
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true