server:
  port: 8091
#  context-path: /search
spring:
  application:
    name: microservice-search
  profiles:
    active:
    - dev
    
  zipkin:
    locator:
      discovery:
        enabled: true
    enabled: true
    flush-interval: 1
    compression:
      enabled: true
    base-url: http://localhost:9992   #http://microservice-zipkin-dashboard/
    service:
      name: ${spring.application.name}
  sleuth:
    enabled: true
    async:
      enabled: true
    sampler:
      percentage: 1 #  默认值为0.1f，现在为了测试设置100%采集
      
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    healthcheck: 
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
endpoints:
  shutdown:
    enabled: true # 启用shutdown
    sensitive: false # 禁用密码验证

management:  
  security:  
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false ,否则很多点监控不到 
    
info:  
  app:  
    name: "@project.name@"  
    description: "@project.description@"  
    version: "@project.version@"  
    spring-boot-version: "@project.parent.version@" 
    
solrUrl: http://10.255.1.35:8983/solr/Test300/
solr.time.wait.max: 5