server:
  port: 8080
#  context-path: /consumer-kafka
spring:
  application:
    name: microservice-consumer-kafka
  cloud:
    stream:
      default-binder: matrix
      bindings:
        matrix:
          binder: matrix
          destination: dest1
          group: group1
          consumer:
            instance-count: 1
            partitioned: true
            concurrency: 0
          content-type: text/plain
      binders:
        matrix: 
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: 192.168.35.153:5672
            spring.cloud.stream.kafka.binder.zk-nodes: 192.168.35.153:2181
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/