server:
  port: 8092
#  context-path: /consumer-kafka
spring:
  application:
    name: microservice-consumer-kafka
  cloud:
    stream:
      default-binder: binderMatrix
      bindings:
        channelInput:
          binder: binderMatrix
          destination: matrix-topic
          group: matrix-group
          consumer:
            concurrency: 1
            partitioned: false
      binders:
        binderMatrix: 
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: 192.168.182.129:9092
            spring.cloud.stream.kafka.binder.zk-nodes: 192.168.182.129:2181,192.168.182.129:2182,192.168.182.129:2183
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:  
  security:  
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false ,否则很多点监控不到 
      
info:  
  app:  
    name: "@project.name@"  
    description: "@project.description@"  
    version: "@project.version@"  
    spring-boot-version: "@project.parent.version@"