server:
  port: 8080
#  context-path: /provider-kafka
spring:
  application:
    name: microservice-provider-kafka
  cloud:
    stream:
      default-binder: matrix
      bindings:
        matrix:
          binder: matrix
          producer:
#            partitionKeyExpression: payload.id
            partition-count: 1
          destination: dest1
          content-type: text/plain
      binders:
        matrix: 
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: 192.168.35.153:5672
            spring.cloud.stream.kafka.binder.zk-nodes: 192.168.35.153:2181
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:  
  security:  
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false ,否则很多点监控不到 
      
info:  
  app:  
    name: "@project.name@"  
    description: "@project.description@"  
    version: "@project.version@"  
    spring-boot-version: "@project.parent.version@"