server:
  port: 8888
#  context-path: /config-server
spring:
  application:
    name: microservice-config-server
  profiles:
    active:
    - dev
    
  zipkin:
    enabled: true
    flush-interval: 1
    compression:
      enabled: true
    base-url: http://192.168.23.164:9992   #http://microservice-zipkin-dashboard/
    service:
      name: ${spring.application.name}
  sleuth:
    enabled: true
    async:
      enabled: true
    sampler:
      percentage: 1 #  默认值为0.1f，现在为了测试设置100%采集
      
  cloud:
    config:
      server:
        git:
          uri: https://github.com/waterif/matrix-config
          searchPaths: '{application}'
          username: 
          password: 
          force-pull: true
          default-label: master
          timeout: 10
        default-label: master
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
encrypt:
  #key: matrix  # 对称秘钥配置
  key-store:   # 非对称秘钥配置
    location: classpath:/server.jks
    alias: matrix
    password: matrix
    secret: matrix
