server:
  port: 9090
#  context-path: /api
spring:
  application:
    name: microservice-gateway
    
  zipkin:
    enabled: true
    flush-interval: 1
    compression:
      enabled: true
    base-url: http://192.168.23.164:9992   #http://microservice-zipkin-dashboard/
    service:
      name: ${spring.application.name}
  sleuth:
    enabled: true
    async:
      enabled: true
    sampler:
      percentage: 1 #  默认值为0.1f，现在为了测试设置100%采集
      
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  prefix: /api
  strip-prefix: true          # false 表示不会去掉"/api"； true 表示去掉"/api"
  ignored-services: '*'
  routes:
    microservice-consumer:
      location: microservice-consumer
      path: /consumer/**
      service-id: microservice-consumer
      strip-prefix: true     # false 表示不会去掉"/consumer"； true 表示去掉"/consumer"
      sensitive-headers: Cookie,Set-Cookie,Authorization
      retryable: false
    microservice-provider:
      location: microservice-provider
      path: /provider/**
      service-id: microservice-provider
      strip-prefix: true     # false 表示不会去掉"/provider"； true 表示去掉"/provider"
      sensitive-headers: Cookie,Set-Cookie,Authorization
      retryable: false

management:  
  security:  
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false ,否则很多点监控不到 

info:  
  app:  
    name: "@project.name@"  
    description: "@project.description@"  
    version: "@project.version@"  
    spring-boot-version: "@project.parent.version@"